//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.28 at 12:13:11 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ns.electronichealth.net.au/xsp/xsd/SignedPayload/2010", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package au.net.electronichealth.ns.xsp.xsd.signedpayload._2010;
