//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.28 at 12:13:11 PM EST 
//


package au.net.electronichealth.ns.xsp.xsd.signedpayload._2010;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignedPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignedPayloadType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="signatures" type="{http://ns.electronichealth.net.au/xsp/xsd/SignedPayload/2010}SignatureListType"/>
 *         &lt;element name="signedPayloadData" type="{http://ns.electronichealth.net.au/xsp/xsd/SignedPayload/2010}SignedPayloadDataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignedPayloadType", propOrder = {
    "signatures",
    "signedPayloadData"
})
public class SignedPayloadType {

    @XmlElement(required = true)
    protected SignatureListType signatures;
    @XmlElement(required = true)
    protected SignedPayloadDataType signedPayloadData;

    /**
     * Gets the value of the signatures property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureListType }
     *     
     */
    public SignatureListType getSignatures() {
        return signatures;
    }

    /**
     * Sets the value of the signatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureListType }
     *     
     */
    public void setSignatures(SignatureListType value) {
        this.signatures = value;
    }

    /**
     * Gets the value of the signedPayloadData property.
     * 
     * @return
     *     possible object is
     *     {@link SignedPayloadDataType }
     *     
     */
    public SignedPayloadDataType getSignedPayloadData() {
        return signedPayloadData;
    }

    /**
     * Sets the value of the signedPayloadData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignedPayloadDataType }
     *     
     */
    public void setSignedPayloadData(SignedPayloadDataType value) {
        this.signedPayloadData = value;
    }

}
